### ISSUE TITLE
安装有什么环境要求？

### ISSUE THREAD

**Issue by jerryhero** [luili16/UIMocker#2]
已成功在android studio上编译，安装app到含android 5.0系统的模拟器后直接报错，无法运行app
10-12 10:53:09.113 3364-3381/com.llx278.uimockerdemo E/AndroidRuntime: FATAL EXCEPTION: Thread-154
    Process: com.llx278.uimockerdemo, PID: 3364
    junit.framework.AssertionFailedError: expected:<true> but was:<false>
        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.failNotEquals(Assert.java:287)
        at junit.framework.Assert.assertEquals(Assert.java:67)
        at junit.framework.Assert.assertEquals(Assert.java:147)
        at junit.framework.Assert.assertEquals(Assert.java:153)
        at com.llx278.uimockerdemo.SoloThread.run(SoloThread.java:39)

对系统有什么要求，系统root？系统版本有限制吗？

**Comment by luili16** [comment]
不需要root，这个库本来我是在做一个抓微信app数据的时候需要对微信模拟操作时候写的，不过那个项目已经死了，我也就没再维护。虚拟机只在夜神上面跑过，后来为了兼容virtualapp我做了一些修改，再就没管过了,我是用nexus 6p做的开发，也没有在其他的设备上跑过，不好意思啊，你可以打断点看一下...
